apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-secret
  namespace: kube-system
spec:
  encryptedData:
    aws_access_key_id: AgCZaoWlrTFE4urZr7uPXRgfQ3wEn+rAbKUNbgpsKXcRSYIdZD7b5k3XmSYYIN2gEiKbJAvzbAH57o537NoayPCyJpnBTc1zUpPMBELQMgEfSQhVc0YIOOvoD87opQFSraG9IcvkLDOUbtcFdTDiLW+vHFLRqhcwdn/texJppH/qbsozNso8GIqFY8Nrx4LdS4YXLhFzEfuUhyXvo1NfvCR0wjQfRvK2qGmagddq3KmtzpqIXkZDtxt5OyL6Cr6AwarZUzupzznHJ+FaBUt9WAvrw525TN34k8fRCE61bcNufd25qSX4EwVAE93GbCPv33o23GjsDus5cV2ZMuBsKjkWg+ANZ4X43k+PJ57oBmzdDVXpWlXWki1Do6l6UEhcIvvEiPlcavrxRMYX8cYrUtHtOi6amoW2FSceQ3XPXdnWSL+rvZgAW8ViGPVvNRnhdmZi98JqWih9CPSVvGKePw3aPZjdkQKkeX1v73Cbu1UmV7EFpCw53nivveKjkwsFz+WeLxapc2Zhr15UUb6X1F12pjZn1L7x96nak/XIyqe1bDSaldWA2sAxQ6ctJR4bDgF9WD0TJEo5bq2deERZVMLYhO39dqbfYmaOCl4x0wzCD4sV6puoZZTY7uz6iLb3F0rn1nKCgTDx/X5/ga9JV9uaCNJgF7DLG93wL/fLdkrD1r1iOD/05o/6Hb+R0UJAF1MBqMxItNltZnGee7yte2DDZbKXgg==
    aws_secret_access_key: AgAxGPwqVwd31bLNreRqcoFYyKk8kICSVGF1t0aEC9AuWdZwo0V02RBjcSRaBFq76Pu+OiB2ooQLENIUlY0HFRCrtV/GSmg07gvAiNcvZXHxiTyjclED1OMvFinaVpsVOosOhHurdNB3etWP+T5aF8wtUEUjpmCe4pq+59oO5obBV4AmaHcQ2jK/Dh5oYdn8EPZXj2KPnRsqP7P8GOCPKIf2SXQjySZ+wsvYZTLDfM7O2sN+D9Xhl7RrXZorXZs6b8qwbde/0KlcFDUIOjNe90jvk9d2MUvG60F5yvCQKveKhJX7dMT131ZI23lBBivCF3QEZPItlDAeeeB8IxndbBKjqiKRqJwpj34ReITZjIBQhgB9CMZautpN3/TAH2PnLmH5HYH4lhKZc+VrLejVEdun1F454rAiu7rtRB+hZbKkprxv1uhSVb8UeceyvpamOnK2m871ZCslS3hxDTGv+QWCgYXrNlz5ZOkS6pfSwZFvu5BfOuSLVqye/ZPcWV2MHueHiWzbnWvG0fhljIiG41ga9VUM4Povd3O837eSQV0OJM4eAXElggvnhMxzzRrjDiqnSg+iEzXgB+BximM0xbrCbrw8dW1Kcr9d4UPKXgnSbGDnQOpg56Y+t0SP0d2rZlJSgxckgijRB49QFKxG8YLbpr6XGxn3wyb8BZkqt3yAKY5BDOS0Hus2cbxHvxabr/yequiPfSO/h8Jx/aJA6Xlp3kpHbXkD8X8Hb7xbhBWYQQL7OiL2SoBB
  template:
    metadata:
      creationTimestamp: null
      name: aws-secret
      namespace: kube-system

