apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-secret
  namespace: kube-system
spec:
  encryptedData:
    aws_access_key_id: AgCoqADMaPbslaPFpW2kae7fMHyhot9gF9a1DbcTFiJZO+t1dQAaBz6wnbraxRyEWfkcN1PWgkxM+EjflLOoN0p90h6a/K38kbmx3DLhEiQxPcr/IuyIn5E/gvwskcgMvMq+yhcAj7vIg8kss8/+DTCVUZnoLjPAzLtBHbg6O3ZXVnLpXozR1iJlKP5sE6ndYy1IcvJK0g6IY3FwBbOad/EUeq7WF5EX0V+oJ1sYdr1gcfWZ4l3tqqe/3pX5A9cLcUJVT7gUX7A2KbC2m0bt+m8RKan94wNFvnFeje9uKWVMP6vgdUkTpUnbn2iNXDemHTSj3ZryGVnlA2c0NJoEYvoDfHNLt4X65BnnaBSu9ed+Cyv5XWm1yMnLZOHzF28HcBUVFkziscpLXQgBmHEdpw8FosRkOG6b1XNxSatO7la41C5q/anVlXBRXGVxGLtW3Cr1vrr+cRITyKA/GNFfD+8DIp6maWJhPS+WXv/1ejJhoPn/4XLKSZHrTeyZ+1XaIZNpA62UyQmy/Dw59X2idOsCm/jBZvQZfQ5dGjlzq9rIC5BbaR7/M88yTnUtH7GYNXUxArapnZE0HjiWHw2mkwHA0FufUQxgwtn+cXOSBYxwjyOfGR1E79zEWt5QAGyoTd3Rd9AvDQQO/zWznL9iGQ0soCgdGwWPEGNm4pYDhzNcV9KKj3kochNfGxZ1LFb+Vjdb9k8FesOeYPAaH1mmdCxnileelA==
    aws_secret_access_key: AgCkAo/teOfEuoAbMfZbVA01oZezCoxCKM8sRqmoUt/PPeAD87M/mGJEjaK8bO3mpPVN3fH43URnSMkwbN5yAAeUGI2E9dKPJjGcXnw6gRaX/hEILhpUXX/m+ZN0nFbkGgfVXhIVFwDL7rI/SfuOI1//wUhjTMn8tMT3tznVw7UOZz/u7oVGmBfGRvMuz94VZ9VlNabr1+r6GCt7t3nQYDZCYAgghCEO/nbR31MtrkIS+G6vbOnnSwXo/dhKuIb/62JFG/mmEN9v0NGYzm+zki15ChxqTqyKkZt6iN4WBW1foEW9GHKHG/MXZDjWMWtSyh9Pz7/UARK9KoTlhnSubaloxAqapYg1XKxbgrxpgyDASJXQImS4vTr4qgbGPceBEdgXn063OJn7CAizdkswZUARBV4NBjyBfYnpHogNmYdUuTPfQt79nuz7K8WhisyAZ737tT4rboiq9TOqGAWBwMO3Xonu2zlA0G66qc3FX3rSENMq5EWWA2Lr3LHeHkclX8LpbaBBuouxDl2frrZdzLgsWE7rnJtSJf4rA2hwmrlsQFeH55CzSru1mELnu4eUROOTS9mfxSditelSsJYXn6S7Nq6WinTzCCVeRQ8scOmS2L88RJaDi6G0TWdVDCaPnT+B51Xe/leZuDEy5sjdqP+qmzhaz7uCLMVF7viWIAO0e7ka/XNtFXalFenMALw1ibK+MVFNayUlqAmjw+drwgKZAJK4fr/C4iLl/yt2/XnSRqyj0SR8NlHa
  template:
    metadata:
      creationTimestamp: null
      name: aws-secret
      namespace: kube-system

