---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect
  namespace: funkwhale

spec:
  redirectScheme:
    scheme: https
    permanent: true

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-redirect
  namespace: funkwhale
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: funkwhale-redirect@kubernetescrd
spec:
  rules:
    - host: funkwhale
      http:
        paths:
          - backend:
              service:
                name: funkwhale
                port:
                  number: 80
            path: /
            pathType: Prefix
