apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-secret
  namespace: kube-system
spec:
  encryptedData:
    aws_access_key_id: AgAthnX08RByrffnMFdadsBl8dlENmdX26wxwyqZq2Lg+1fyE9Ho7zmiYEb7442zbm9fIUvOqIT7kN6NOKCHYj+xy5vf1SNgYWi1JlmvMWuNvpl8v58kGdeViUkBcZkgqwqIDj8XkXw/j1lgaD+UbyRzmpg796HDZ2nVgn6a7Rl5PVlOKtP5PxYTdIlPPnQ7KQrtEUARR9x8PI+mnHyyZAuoSm/7KngfVizfMd4tdmQC0oVoiPs4dWkMATKGuYeoVV2z2Vp/M1waclx2ig4NUiI6MjjbQ/99L/U0KpeCsUZ7S0K5NQHfbvQKjoo4QKlk5106yLSkJjPh6/g9ckCo8+LpKAJxnQUOrQIdX6xJBs6dkXLbr81lnrtRFLQlFNiozP1RSXBqdhKa774pYCx8OP8ECRODhxMLRgDD51e/F7xcbxZS8PTtdfplB9NgAUDDpn7GG/9LxcXl2nKJ5oFr5XwoTbNcBFHtgSZSMX4pgaw0emhXhCd2wzw0/7XPE+0+i71W92cr1fgsFuLBCaS4txwIjZOEChlJph45BpGdNCznHg30b6pse9oEp46o3Bjuw2WYqthDLk6nF7Ffm9w3xddF/oVwrzYLWP7SJtBg3gQMgf/eBANc0VPX4d6up0lvkIeGMdkaITuWwSig8H4qTabUFLlquDzk5VFnoh9dMfdM+YdSUShQaqtFe2u73EeKpA2uIQTzLKG+kSNGoAHEFYjTR73xLw==
    aws_secret_access_key: AgBoDBOta4RMYlrY+grhvam72EREJGCm/RSR2EY1YOi7m5RVGzKFiFjgPTrLydfrrKTHef+V/8Q1RfMdRowKJ1G1Ey3h4dxq4cDfKdoTt2qDRG7ZcVuMpMYNFw3f7ifRsoBmnRyRzrAUeFkG2KJFTEv5+l9+lcZP++CYE4c+3Xp9SLv5LENcEwQ+NjALA06OWtSoCtEdNe7P3PROqYDeerzVwFULpzyiV2/AZout/kxltb43ZzriRn3wVBK7Lh0MoedyLx8FjGYaGWZFQL7t+JSDEQ+ucE+2kc6buuyQuTOSRLrBGHGgICuXSuUoNY92fax6FSUKkJYc0dwLpVqQa8LPThPXeHi7iB8Ufr4mMXyYpquNYQcJ6MsP2HJ0Br+0fH5tYSpitXnSHhvMM9n4F+3yxfLAaz/7yANMQ31DahElDBfVbcoRlOg2PoKWFMCS6yfzdWt0SD/xJluO1qQHUPoDZDmwRjxMs6+GLSCBdNhPlzBsNatJdBZ07Vsfd9tZgu+Bw4ECU3ZfHcgT1ZE8g5crlrjOLFXTNPzYQDZ8HgTomZvlbEDFSu0wCxheDziv9KuFN6Ic5nUqKHutDpQ+FSZ+JKJ3jDVo5XVW7a78E8OkxF5pLzd9ug0szOuhEV5wBkhbxMQxquJ30KH4Y2ApTmv53UR3vjrpw35imVaP/82XOIFw/2M7s4s3ELiql761rrEuARLVxdSkHxc35cjekd7sreKDsNnhYoIobTYWk3Erp8D+QZZBesOW
  template:
    metadata:
      creationTimestamp: null
      name: aws-secret
      namespace: kube-system

