apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-secret
  namespace: kube-system
spec:
  encryptedData:
    aws_access_key_id: AgDMINRgh3VrLh5/wXSpycwRSW2sVAYeKNYKlw2GZzn5MqGA+3q0om7lF/Y9rZ+SZXlUX9z8D4gW0S7Tz91Y1x+8DIOUeVax8XsaFaEVbExU2UOCs9XsFCAW3NMcRsDITAft2XyERWuCCdb/9Sg96JuxE88F2Nbyk+CtO0SRMg+J0uqXM8P/NlJh7e+jcf/r4mNxFKjyxsr37BT8KHjQ92niFY4s3QdHrjlbVtziAK2Yf2GXIiWb11meoaRqhyY6UYMvD0Nd1dfAE4frgj9tC5zFlU862b+udUC24g2GZcthx7BLcUrUw3CxS4qJSRJyy8hvHGQ+eJn1kWxKXBwH1wx/jM2eDp2Hdc+yfULvAuyw+5Vr775qEU8glLYziotyjsWJ9nRuvjxhOg+Y9Q98RoGhkC82/d40IlhXyHsZs40Ky9Mbpa0kkfGaNogqhFBxwWRRN0g9ff2cfU55PXWFIGrgQWikYZ/MXM80st9qQmLKBxX6WK/PzkAPfXeUaJx+YSPjymEp6SegbCtypW8G4L9OYf9OwADex0SVBWwErJXkM6MqyecdZm4wIqT3TkJoaGMPhQKMVrES+UTw4KZAxgH66PTFlkVjljv94+mHuTdQaC9UIm/yxLJaCAIAb6F36CLTPk3HUqHSaudFG0kqyus7OIPGSDowRCuFdpU5HSBXhsgZl1asX93kGmaIpodTz2oeOOJXffF6HHx5YaZIiKWobj6JHA==
    aws_secret_access_key: AgCoQp9Oj1Qpri9cmMkpyrwlZp2//fWNCVogsNtVj0AytntgQ7JN9RxPs7jXqDMMcBUI/8YQuiu9P0EzD6G7dqycvP/Bn+wiiRHRNN4L7avwEdsQ56TJFkzPZuaqNCdWv439CXjV+UXVBZJ5yOEb3+H/9k5PBKjaa7Beolc3EOwbHu2gp2ZH7gYNC/L4KAf1gQxnb5MyH8hMO5ht1ntnSk24xWdbItrFFkf/atEVmJDCXbfCWOtz7UgRzL2BfYAlpXBZxtAdtCO5rQfh3KOBKrN3+iLbU8rvK+07mnqkKwJ4oSQMwg5xOEUg95UEXQbXF1yTxi53oJjLDwxAaZ66Kp0KFZUHwi5h6Xd1PVJRhde4e9G+qOu/A/TQI2g6jzr5Fk+/6jvdizfg8yvS3tewmikcIVMdleknAkbtVUETPwD0CjOwhVYahrR9p3CR0QA19BH67WECcltXaRJ94Z5cEjBqABOnajtZbiRA0aTk4QCuSPlqGpuK/SX5RmX6ei4g0uZApUGzMasLg1Pj6EY9OsGdPmRSXZroGBoDGjS98x2FCJGPg7UOZoer9XkMQDEz+g4+L8lCHjCUWc5CxrARjDiOFKnLwdiKd9q3Wpq0KYVTcj0HRUXHj/VrvJGcbyJd8+CjibmW6avaqd/yroxMy3feycHoQ0yKegr9zh7kXxDEnd8hrVpZIVGeCu8xjmdmDrJ2kNvMFMEqoHasiB7WydVyB6t4c4P2eLrmA/F2MBEkrwUpOi7F3Ujl
  template:
    metadata:
      creationTimestamp: null
      name: aws-secret
      namespace: kube-system

