apiVersion: v1
data:
  password: c3RhZ2luZ19zZWNyZXQ=
  username: c3RhZ2luZ19zZWNyZXQ=
kind: Secret
metadata:
  creationTimestamp: null
  name: ttrss-basic-auth
  namespace: ttrss
type: kubernetes.io/basic-auth
