apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: webhook-catcher-data
    namespace: power-sensor-monitor
spec:
    accessModes:
        - ReadWriteOncePod
    volumeMode: Filesystem
    resources:
        requests:
            storage: 100Mi
            storageClassName: local-storage
