apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: karakeep-basic-auth
  namespace: karakeep
spec:
  encryptedData:
    password: AgBW+W598LE4D97m0jLBPBt+wrMzUWoQE1BIbo/0YuOgRmTnHQtBBa/vu/xmR1qshkq4W8mxaPxnIyxqI6ezO/Uc46YCcbjiMVCk51HR5DENXWEzyf60HleYetqS2nHA0M3eNU75oo7yKcQMVyu+cv950YHxqv805wcmvill6nOqcNl+HRemoPoPhkXdgezVHt3dPe7eM9zzqdyS4H4GvWFuEkhK8xZnSxKlGJhaKFsgJFdEP6GbkbHIHEDJfIqglMGBtIn4DdjMk+wrN3z4YcIcI2Hy95fmuxQdJ8gSo6pepBwEqaNSg5yi8zvxRDLLgfXL8ThNozNW/snv/NkTYiURisqgSVw39ywX6xZc29U1Dytxz67OM5sBWpJWUzrWP3NF8BBSVJiuETb5gTzYQUrmOx8i/Qic9eel2tDmEBlaZPG41eH/m/UTwGXHDgy4xE9U7SJ2SAC+BBiSNHFJWE7wl5vAizIwWf3Ekyy+sAiV5sk91/WXOLmbQy4R506MVxUFnKCGf+AdROUlfd640dduxlx/aVvOTImFzKjawWWdrQWMfuMuLKV5mrmoQedyAlbul5JYf9Rv3aCnoVn2ofeWpscnduwaERLUfo1enY/OvhUoslEjnOn4EoHLGB193P8rk3Ym+tnttIMFAlpbFbYOKgUYX3VDmwo5x3efnid2gQRoFrnXjBDzqX9EQUF10B2u8KjFqM0YIw==
    username: AgCIpGAM5YQavj1W4lAbrr2YBKrsHaNRmiX88c9Csxlfnp5MG2SmWATbTJbsmoGq9RApGoHJe93R2Sj2OriAF4UnavX+jt8JELQ8MEziz3t+peUzuDxAELdmdB9OFCA7EWa2QWqC0qqbwxRWSzapTv/oE0RVOGETxKrMjV8vo8yQSURQtPbublftR9ycRDZbTR5pLLKnFzh1Lm/2QY4PCsz9HSa+T9ujqE7aGKb1iwVmBUq0eBMG/rm+fq9GIrfibNWgwV7UVyBDTercEHXMbUBKgopFwpHscBp9z5DztmFEjZ3gQjlr2tnDJHTobhol1DP1PlmxV8IF5J2/aBTPEepK8eGIEhndrvXry7hftXLk7/vLG4izGIse4lpgu5T3b6QFN0YQ0YxbcgnOl07gFCzmvN/veuR3ag8Mqq5eY5ZxD7pggX2oMCs2qTAZYposq3lDTkGxR9eDqZSeOa3Th7cu7pn6TkMoZsLPmpCGRcn3122AXNKo2DeehXgCQCiQkBQholOqCQGSXAxI2TRLnJVIamW/di2KX5/yq+cYkSPWFjbEPWzomCzOkxIxbKPHNO8gulJ2n6vAigTJt+kigYISPHJux723BxdFgqqExZkUVMXw+oxJ3X9Vx7do+Q/Cq9wyy5NsLfG/nQpSZV7HM4vJMyApF7+mdln44eUPAs3EUEZ1M5bjHOX5b3R/gWe7FltL12OptQ5ODg==
  template:
    metadata:
      creationTimestamp: null
      name: karakeep-basic-auth
      namespace: karakeep
    type: kubernetes.io/basic-auth

