apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../apps/base/coder/namespace.yaml
- ../../apps/base/power_sensor_monitor/namespace.yaml
- ../../apps/base/ttrss/namespace.yaml
- ../../apps/base/custom_funkwhale/namespace.yaml
- coder-db-creds-sealed.yaml
- coder-db-url-sealed.yaml
- power-sensor-monitor-sealed.yaml
- ttrss-database-sealed.yaml
- ttrss-basic-auth-sealed.yaml
- funkwhale-separate-secret-sealed.yaml
