apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: syncthing-basic-auth
  namespace: syncthing
spec:
  encryptedData:
    password: AgCOzLmz0K+gS4JvJiuQ9TKFM6WvVUdmQPxiKyNKXHDE9tZ+qEe0DBI9pDNRn2yuBSySfflRGNI5YcO0nX+gu0v5gulZxv/CBgMH0qd6TFESo+RfUgsdCe7IXcHIULxWw29SYaKNCHg/iWSAJpTuIXHyiCNND28XjNP35iGBuKX2GFYdCZqJLcogzS3v6S9bbEFBntfMDkYiTl+IaQrkD/bSTtO7fkg93C4jEC3NtCUPnYc6bb2u2hKcEdXyCDXy3kUosl7ilWzUD18MLjcaRgDM+2Ca+5uJzaUAA/dR9LQkBN/93udYaFRUmDDGakeIU5vWmN3VN7h3alzN55tBYuVx4MmrtFdIVoUjXm7R3GORMTF3rOj5XDps+m0/Xh/m5ZWiKXp3KmIGFXUL84EeRINz6LoOlm84O1U42api8z5l2+gNL94CsOvIbgsQwBGaLvdq5n28ZoGqz1ZXSkXpbhLDQ1AeogGWj3M0+NjrcXHCPgMsNskd/X6eBOaJDw9DZvdLJwaPp3kX6EzHtvYafo4e2Od+fwpvNdVh7AJmwL0hr7nD/xGLnRSTwGcZIvNyZVnYAQzmk7rvTw82IrfNrlVfzX/Xr4Yyx3NajNzTHKuZRY5njUv/cIKBa1uBaUaDMaezlhXz/ipHQNwbSZVQ/xmXREW63UVxnNKFvMuxfrKCFFWMZWua1qwFuD8ylIGHyaHOi6FAaP9Uugc=
    username: AgBIDTgda/7GCURxxHmF1+8UKKkMOAFk3BrewdldtHUByAyB3Jw1wXE99HNPvmro7tpsv/IL10aujp5aNSjxtLs4QWS/WQhtpaAa2Raj73DfsCvveWduTrp59ByYszOalCkyIUqHrdtb/KnKDRHMzc9WW7wlqrWaqddFRWb1fqDJJyRwzwQtalkZnQC63L3br6w1sd2Q7+7MxApn6LeGAzV+5NIbPQwJbGYbVMCY/lglOanlDD7zbwoGz4WpphjN9JrcrLTKmvpLncghkphX+F8nWI5YYw0aU53qAyeeE520EIKLFX9hsNyBlKQintjTJFWr+tgNn409AYaqi1zvj6py1nQd7yNpTlNp5ybkR/zMhhbrPxoVnq5xUg0U+Eri5GVaIv4TCdPGtplNW0qw8Mrov2YvqexV1mRXw4mDE7qL6g7y4tR7vGeMIBSuzBKe5v+UgBJ63Eb9C1W/NEJrUfGqdQnz7cj1JTiGu8JxtWXIPLXv8wDXcQWQpf9GB7uXZduRrvOSPvHKyTAka4cH4XN2Vwy582Em4hRJZTvcZ6XKVp55xfHV048jWGBCdUeHG8+ZHEBeOZBEmL/NREtwnDUQ/4UWFrd4teorLSC6J20MVAvw9rjwj4CGGHAjuvMWYAD96vq99QANVyogNHt4vejJNIs3kIQahNfqTS8RPv324m7Bms/MQl485T4rDPlfdEM3g5h1FAhaQqQ=
  template:
    metadata:
      creationTimestamp: null
      name: syncthing-basic-auth
      namespace: syncthing
    type: kubernetes.io/basic-auth

