apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: backups
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: apps
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./backups/production
  prune: true
  wait: true
