apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-secret
  namespace: kube-system
spec:
  encryptedData:
    aws_access_key_id: AgA3+e1w7oo8HTuiD5kA1a40PtknxBafzqXBiv/XqO6/3yIh8d/IGyxyA1BTEZ9XhlHnML4Vb+SlA0LVtKeiSmzkYvUtRJf0LzB4GuLKAojoedjMaWeiQ2nI1XTs/Nhr+YthWXLr3GFPQCglr8jpa1ONasTdm7aRXK9SZjZv5fGAno5SLFDwwRHrdPpBSeC5lrtGFkxT2gE+WXYYSbk3+n0wJ5BTdWwoO3gW5cU9AQIXiNellFQBR8f9IWI9nVN2zwAr7j7hstNlqjaZOJp7ar4Jp0R8hOcAc2c+NED8PP+6wy+GpPb6rjkjIYEIhpOCsMIxIDLPza+4HjXefYrkZw9fDRoNrQuGiAlGludPHroMxhyrtrm+KuhoAofaKyTLSHabSP4mrZHKIcJvzLdDnIT2dTusBYsHCFaPBncJLxQpDRBCQyMcLt3f3U8urfhPInPRgfOkir8h4gWg/ZlLv5YI7ZLSp7dKc2yJiX71qCfLpPJmmfVwo6cb9v1zThrSUJ0kD6auvYp4PSe0flbZmPOxIQ13/kyc99y3/BE1g8KqBXd9fYyAK/cB39n7DiJbJ26tg3CQxVg6raCuyS07igzYVMrH1uT3QhoaECcqfIp1fczTTy1ee2uv6vIuwz2EwmRzU/StOmd4AyWXHE9+jPXY14l9+54OIWXMHb/rIE1QD/Fzngr9csHflZGFVA0MbsWH6URcT8exztDCT/7ITkbs6q3Jpw==
    aws_secret_access_key: AgAYQUbtFk3UikGijTDJYZL4Jy3vEGVOa+6hdSpeHoQeNQv2hAHAwFV4zLslgE4xEutZtxaBFKb47BdrmL0LGNWTynKEPu32iPMA/zdHwqJQ9wIGGaPjYdQfFjO9tgKsjm9upJ0zN5y9ThNzZlBE1WNgYef+HWiSZAVQFGyuNFi6nHfPgdMHbYgHUgtxl4kpqAZFajVDdHIIjqIWbpKeKLrj4tYhDwqs8WE2NK5/Z91Yd+F+8lOn0bYyLklZNqAoixIfE9irzyz76T6ydDAwQOZQqBC5D5zcLwCWLL4tjT2d5p0mrNyu0U6WbMaADlbxmzGPhCfCiPT1UwFJkeNHQZ3NaB+ERXH3vt9H/OWfkeEV5YpIMS28qF020PX36hkhbreo302ZlttS8pg4kJyX0pwpxxbQ/wqgZ9HoW3KQdS2C8P7wrSFen4C6ys44uEZGrAXjAys2o5PxJkUrvH2EPoLZTGIvQ/HNN25c164VCkrueiAIzFM0EzLBeu1WDbJ3nk7dsnTQE3dLSKwOA7ClTA7nD5QEQSaeJnYt5aYin6r5joJBPmiDQHKRQWgDPDv2O25s1QS/1djgrwTt0wXtRDTl+ITxjpYd5i3ry3CP+CVKJA9T9Ybc/NsQItfCVsWcErFgXIIGv0PZEU+tB6zdHGNrN9qZqbYEEckYZZqy+ZfsILJfZd6KOruo2WB8mxhO65xVC0c1uSphUtR7/3Gge6nY90PjOH58FiuInaw+rbACCVZvDOQnNsqC
  template:
    metadata:
      creationTimestamp: null
      name: aws-secret
      namespace: kube-system

