apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-secret
  namespace: kube-system
spec:
  encryptedData:
    aws_access_key_id: AgAGtc8Yk/w1iwNgrbqI6lg7nIwQ/iugelQlPsTETVUDYUWvyCKx6UA3TvZ70kRohLZUjbv6f3d/y+APYCFzeOsSX26F2StaqcFDuW3DkyAR+r1/LKia5MdP9jM0QnCGRiF3Bw1h4e4/9MHvQiv1qOMJB5REAgPjbE4/+gQJjT9NORmEtT7gXeBeqwpbN5BG979wgHFzdLo/EXMeprWhkvO6NPnn6xcT6NQoTDkFWuwSpWTMrb9uGnzfIxZrp9jcwgsu5xDdGsei9PdkreiapFWej1ieigdsMc8dXjCuYBUNh4VoV+NQ91UeU1xd/EtBiu6nAhKzmEMQ+CMg1Zds5tnpmSuDdGPHgWBpR+TwQq3CRvsl2R6uRK04CZjTCvV+FhU70kXnUrwoG6oj3crrGmbD651Stb2tHpSgSPBn94kM/Tq15BqUFNnxcTEAPK2DxzjuRg58V0h5t2C60dlMFMO9raExMZglwjASofX9p84a+QT+HMgEJkrBvyZuUjK+tDAK0B7VvJU5/H7oARfkvNfpAcg0VHm3hxnJHtKu7qz1pUQ/rDHyW2n5yE80jLvV4FgRAXJ8kxrnHbkcLzFJwhoKpuylLsoHdwFBzDvDTy20EM1aA7fSNyW9zRDq93z39yMSRVAqERfh+Y3Uzoy06aFTMi3Fg3PF8ozp653RwvxcsiLSfAIwDzg1CLG5DM92rrT9IYa7/Ay7ZpA0fDZ3nIVebYUHKw==
    aws_secret_access_key: AgBUBKetiufMLIP8iN4X7bpqwJCCBdTokQtFvUZUKlxvsh71QZ7xpblCFuMpcaiPn66MnIT9k/ApWTxvrlz1AP/XJfaAe4s5bRXF9tWFDeubi+i5pk8qYiwG7XE5jluXOzNcwC1gmHShD7W6ngNitecwUYtaYITMVKxYDMIFulMDuH8rinI0qfBptATeufdFLVcgA0SO8BjI3WUG2hQrlTARJMIXM1hNuCQa/+l1mobE0/HBKGCp9+TcqW1FcPdilH12wy8T7jsyCZ7X2YZQUqxMCYsn3k5S40c/PUbNxxVIKfM2jGLjzS8z3yKJq3IEr0DT3S3pe3XJhSyoEVSi/tURdrNOXtd7/fSBR+04Cpb/Bw2lOLmNAPwBQYhHglyuLiLnM7pfFd4hGiEJG6/7XR/QAh/jAMdVBi2cOL9m3oIDQod4i/6HXz0t+bxuGuGusknRb3Igxdx88P9GQB/CgR7ZdkqxNuOO9sZUw553fhgExdcBslPLpvS9XhmCfFJdCHkboh7KOaekgV4rThryM8fMLCrYNvJweGAw4U2Qsb9Xk53mqv3ltrMGCY0R01m9/02o24OCAIhsRHwFKII2lwJvrBhn/JKDRTt7mgwGoiGHqCUkzzRhVnmslZxEh69rO08TMPcsJyj2jW2x7RL6ITY6CTvHFgflk675h5TYNf8pxnsWSfaLZuAU/3bBzGJVDBZIUgJan9bs0xb9CyxM8YI8BpVV1BhmYppCOEtASNc+mTXbJnfkW584
  template:
    metadata:
      creationTimestamp: null
      name: aws-secret
      namespace: kube-system

