apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: karakeep-basic-auth
  namespace: karakeep
spec:
  encryptedData:
    password: AgALfZYtqArhMyINlIObbCqwsJEIxzt21E9Zo0z/g9MEoJzxWTy5bbc2ZLFIzmeDmRd8JEa1AJ7zrYX/ocjyERg7cur1SODHE/TD5dbKaQ+YQmgAY9Fp/5Y/tAuW96G9KU2fcEfkNQmfgQxR9I4SoKcOiPIn6GSWyYKDsckm0hJjJhK9oqku6hPoFQdQjnxh93v3nb5YkSuMMc3KDs1eCYzbABDcu7Vv9s9rYWWzATks7ylRy6aL833UZEKlLSoHZnQu1swt/R7wWP4Ms2zyeGkjaq2lOEpDajLIvozKqpRM0cFHAc2/zlK5YkeW/SLrYj0jWCBKFi0h61MaoXlUKNhJhWv7KJXV38G9YIhgXUWXBfzLbP8xbw9MLeHmwceNwHSZTF3MpYr7BdqKrb8lbDKjGWmFGzwJZjtZNo9YKEfoukwn9BWOX8h8IBgQM9JPzpS9dN/ffJ2bNSlPMFxQJO9ezQca2aDhF+GjUSVEL9oCK77m87R0RZlxnhmOX4L0uvODYZUF9z6vYVxYIfD7w5MJUV8WpI1H8H7wsh3USixQnnkiq8VGrCmZMVFLVf3XXimkT9uHIFR3y/vfC/revHcpJNpmM58F54VIejk5uuHXqleGPVrbIw7hDl5uB7Awqa8WBw9n8Jmprs9FK7Vc3sGGi8+DiayV8jfnLkFKpLNJoN7NRllcXXk79rumeTnYJroc5/00qnc4VqGeHDbl+IZOowShIIz5od4=
    username: AgCC8b22LO6eQUScdjk+jUTMGKDlU5I9C5Tai+iItd0Zzuae52t6KE2qiqb1jqElhZsuogxbNiWz2BK/w/1iOgsY+4p1DqN+5LjoJBe0lvwCBTOK/+W/XPk89+PYiJJNUq0pHAF9lBZstMX9vjHy5OQXFZYoZEAy6d/0EvxuKUmCI/vvGUAOjqeg0UyuDfdC5LGMObyOfqz1TB/yWN2XAgkXQsLeTff8LdijJpRYpu0sr1ibr7ODo1J34D3927D2E0fPeJqy1fgefEj+TWpW/2TZ4ZLmzXcIOkJ3ejxix20M3L0vGdheoZVFSpfQtYNp0XlABCQJpnv5FksCoGiiuz9GCvxNG9QAgGCJqsA5cEm0rCg8+XZXcrBtgvlkYVWMD0UA+DwaZ+Q4CNS+xcYf70Fmq9Oz/gLOdFgiziOVumahCleKS4WuvOO5do69+O32KSBwDboVL/j5aPvzNgX3NI67jKfrYFnSj6ttO62sGWdUe/5Mip7uN5RkrPtSB5ZLG7oE0BjwWAImMKOQyj6WZJQoSt7vs5u3dLU2CXkyoB+CqRwoFn/pCPCtwsv9Nc4y1OwvKl+kUwrcazUB6xKLLM9p9Xbk15oyfY4gmf3U8eaFB/pVpEoeSV185oVsUlHIaeoVeoGd5BRQKrKi3s6optPWmzSsM825jvv8SzsdwBw6EMaE5lqXZAHs9UuSL67f59vU+NIHHTU=
  template:
    metadata:
      creationTimestamp: null
      name: karakeep-basic-auth
      namespace: karakeep
    type: kubernetes.io/basic-auth

