apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: power-sensor-monitor
  namespace: power-sensor-monitor
spec:
  encryptedData:
    readkey: AgAAMY1Sv+XpFzcf3kAxJVguwAQNNvm60NvRCnBaufHoHr2bLJHUWpyu2uuYK/N2bJoF0cc2YSWyIGpmqOokxufmwlCkW1Lc6P5Bq+I9Jgy0yy+YvwYeoyp/X7nanGh7aU6jlEju1y2deQn8/yuaQ8Gw0Sf72ifPCqkDjUpD7EOThGUIqW2eNmV9R44wFwBgA1g4G8QWiMgXifWrz26Cafr6RK0n9NSJhAc43rMq8hCQxQTlzbfx25zryH8COJSXqRycWgiv7S8ZJuYViizYRfdyLYdmv6/Y1yre9+MJ+8K4nA2rjBRgRtsd6LZsEPFy3cppqgGiV4DtSKyjI6JqxpNDrGM27CcNH8g0YNz1NToLtcdOPhTaMahqHtyzhO3iRbdcl9PggbJOGSbm+mA4UAPWiWA2ZxDRwDwJpKZQqCEQSaowKeAO6LAzycDekkU2aZG9QXcv70cWDH0+WbwQOrGs9pIu63kxad0w9eYVMB6nur+XnaUz+Fpu8ghtYkPhji9dnCFtimgpKjOTr8KY9DlI3us1FDdGqeOtVc64KIn+N6B1vDQ7GJZcqxZpb6DpF0+uQdsWU/8Hk++5QUIN44hflLTSOlc2w+zMqZA1aYxdORUg3OEOb6KXSC8NxqQM+AnJuRseD+aHt5YIB2e2qXfCfYlhQRtx1t/Z6451OR6O9L56nB+pJbWXRxIXbluqqbAYRPT8E2Pwf4NfeezUop0JC9y3Mg==
    writekey: AgC4bVxurgLpYwUTWam18b3ySP0V3WwRXN2/mNQNibS1oOJQgDSsQMMEcEtHOo5geKrl7xbUARPp57T3xTdb1EEVLMkVxWzIXQ3w4xobdvW6HzJJSh2pqVWLDDYUmulUCbVwaq+SKoLzp/ymGs8n4cC9IovY2Gzjl/xoAvZIexEQEJtWJ9y7/iFSYnW0x4f1a35deGpV+/Nkyp02Dz4F0VXpYJ+DUg9VMPzIwOqwt5NkzIT0g+Hdw4H0OLWFs1YlUdyYf+qNipZg4ZmcRtHV4kY3V9ywS5Yoe45GzX541/lHmlLJByLxAJ0zQ6K+5R4Tj+OiI0dEC/6NLur/S4S1UXk0pm73pM8GQERUSK78FCAN1+3tDH9l6YC1ERmgfbCL7eVuk35oLiUkrhkbs0AvMi70x42EeGBfcrHI7fGXz46dfjFQwsA8TeqAmC49xQiE6p9C4vY3EPDbnq9KDMBH7IJCUZ0e13mQbxV4HrtDs9PMZMIHyl7EDTlr6f+JYk5am9bsn3oMteBhDyGimFXN1Mtn8FBp8robQ+wLY8f9ic38P3Q+cc9VKBuLZC9XcU8cVkaJOqi8ecADIuUsOWIQPWfEwpiBpEA07VyWfUXwyX19XcL+3b6vcVQMRUCRzzVBz/DHZqEZVuCqDFkr9KE1hFWdk1N7L4Dqp55Kt4RcMu9Kb+KUkOljm74exCWe4v6CEExi8n8fwLbTMIZfFnv3viE5VdALsA==
  template:
    metadata:
      creationTimestamp: null
      name: power-sensor-monitor
      namespace: power-sensor-monitor

