apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: syncthing-basic-auth
  namespace: syncthing
spec:
  encryptedData:
    password: AgArLweN4ooCLLFZrsbcAPqpoqQGkKnd6F5YghKKuFDj1kuMN1KYshYt+q+x5WuUShJr11QY/Jm/esnqsop6M4MTPJRxnfcJRX/7CZssNvqJNJUoK1QBQ1KH8XspIHWpTm87u6Ym4G+jpBxHU8TtI37kPRi5ClMtWJ0DlkLqP8xdrGgy1h2bmyqDer8eYgSlzAExH8SO6KZG35AqsxOidxSkcUXiQu4ufKRTHaqeP/TxTecB+teEQZzUGzpQVb2IsWrRH2lxxTVsl7vEgZDwjIpDo0tKJuEcruZMk0wz1qY7ZM9OpJz5WfosnxZZEyx4iilciLL6/0qImKy9XUsiXwCwfxTqipEz8zGpQHRSH57sehqiovQChzhlhlsjCqL/Q106nZFpP7vYDSGwGv6+uLD2TyB7X79ixxjupQr1Vea0zACAaoKX8AVkmUfjyxmcbQGQX7nU3UoLFAKrGuX3fXlAoDafOw5u9o+BKJzsvCpajLqlZAmaQKF4OaLYWbpNynsINP/3htiZ3sZEMDw+rW4W1j0rE3T+gEsK024bqfTlnEz5Cq4uDrQZ5A1dBYM4j2IzqldI1I90TQjP+4aRsPGf8qccXS+Lpk3CHdhT7dN6It6PJhwJ2i73togppqAkT1Oz/H6aRQ52js1RQI/ImC8XZNGKpcBnjCU/Bkt8LBPoSsXQaiHS2/xCA1OoiiP6JwOzoXvoEHKHGi1xUy1txOnZOgecY1jK8+M=
    username: AgA4Aku8j3/JUcY7NRy6zg7izLbdhrB0oVikVRJ5vriP8W18jqG04QHf5V6eb5ig7mdKUX4BSw58L2A6CJ5+tt3QtXPmJ0c9UZzOY3RqRGKckV5A30OMQpgYj9mvkARAz75jpGaxqjv+1lXASrvt/6yDLy2Zc5k+dxP6ulm+3W1h/QUqzbx0/GaZD5staKLn0ohHGRI6QRl4rhb7YIaQ2TFS1XxWxdnAR5cM80ktiDChZV1Vv1s1zKzu/mpqEnPCANQ4WebIjsQt2k3QaAXL5RYDWNSQ9wX0vxQwjz9T51KtPUpOpzxVguiLJRxQjozvXDwMjCOHs9+iOZEGmX7wV1j3vH5dXCwvWradhuZrCWyA7D931ROBHO5arPEDCW8rMC5zbHUVIDvxIiEsnXxvRGgCxmYR85LadsnMisMsg8mVoIcv2/ZoY1O9lXNw7Z9bZJ3tJ69sOUBIeQ8kMWLXfiF907R5ZrV2dpmLEL7j0kix2K3RfVg43b9uiXoHhhVsU20MH1bA9+hdv6bx2QIPeu8yFebPESi+OVjKBhuDpb9pLJZjplGET+Zkzynp+S4kHNmva5Mc5y1PKuuvobFyGaGs7tsXNLrCCmTbxW4uxRhw8kXGn+8GNz+5cm3L13OSI9iGd7rfmzWUz8VH1rFDUHsXEnpB3mEHq0RvWGJpZiXCmNp7DBwaCohTSqv6FIwNIi9pADb4PyoXbwQ=
  template:
    metadata:
      creationTimestamp: null
      name: syncthing-basic-auth
      namespace: syncthing
    type: kubernetes.io/basic-auth

