apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ttrss-basic-auth
  namespace: ttrss
spec:
  encryptedData:
    password: AgBaKoVzOfbRaCVxVJhNNpToPKFnnuYLVaub7FS0AxMvF1Amz7Tylodx4o2ElkjKsNLYZNocB5WIh6voLizpBBMcP7cjwSvMSiZhY+laYV8eSIxkcCDpjNcw54YLSh56hQEbTSbtjRLVA/1NnI1Vad2SplZilYVqiJ4JLwQUT1j4qq+A6wgSQBqLSordtBHSkfm7vkDNJQQ1xBbC3lwH00CsT6kDJnGnitsR+lcW/fmzWKgapR1aK/tWdBiH56GMROyrm6cJBk7InRjfEB5IfqosQ+yHOb845t5ryG0lXj9fd8RCdkQ+axxdWXRVSrz0xPnMp4rAY4vbtuvR2NSRuIgBwKvU1fs51uVJNav+5nYkyZkRh5mbkGPo3EXbW5YVKSNN6EgKhhVdY5C769tlUsip/CYaKM4DYou2ehTjdD3v4OLYt5duhPi3koXCiKvPWjZKfEGMFHnxiM3Cod/VUZMUSczv6aMVJZNvTwLbmFmRftVqjpi10Osj7hs5g1ZpZn32FZBRODLmwyX1CocZSU5ajBKuAM9QqzFFoOAApxqhtKg/CLljYu1xdtDJk5CydTAgYgQaAf7vwzOIrnrCvynEybP+tkCq4IUJo/lGxQpp8kJ520YkkNzahF54lzkMe42skblbIIDhK1w0T79sLjMeiflwxGlLNv58LHc5vnbI99iuJnLRpdfbyARnXkvI34D70EhfsmC1YA==
    username: AgCE6VMLGvgOlmQvPdwrsYbIVMJAa7fiX6fMVisAXo8U2Ebe7uUEKoRyMtur6DOJdp7rFFd2AWmKi0qXBIu4Qh+O5uGTjJ2gIMnWLZpobSK7KgIw/jqyGpcKgu8EdPZsLbNNRYA4LPqGGwTRYvY3EXpKQ+nHJyPZvM/nbUpuBgssASxQogMRwsy79VmHRrvYNAeaze7sd8aLy7bhrhUS7NneJ9P97hstpJgt9OJJoHgGF3uF/wrcuyxYzv2WxWnLGBhRLt1s3oV+XHyU5UYf5EvGfTU7tuPA1Fi9WJ9DoROm7YsqkpS6DVCJOCX5QyzHORf0yyg2d/IJbQdzoiT88ukMwXETGYRr+4cgAu8nlsT4yhtvL/3F60nEvj47+v182j46KTT3H23Dm6D/TW0AYmNsc0Fn2a/AMXXRBHcwE1NFK/E6oGFPkOYsZwY+td1nfPh5coKMGd/W8uLgtS5Sstx2259/gGJMyBe30NNNSlUTfMIbmpqcqnpelvd8BPtybcjIwPpLwJ4b578ofatZcE9JQrVfv8YX2K3n64VBKVe4O45borB6AIy9887P2c6x4Lk7ETmwpxV7fw9Wm2fvrewaW5ju0M0BUHDgbvxdFvTf15U6jKGAGaUexvGmDB5uee7SFi13fHia8WGgtZQRZTVuOQEpP0slm10zsPCPOEzIb8w5/B12FBgJNBCsgHl1EHJbKxX54mJ8TQ==
  template:
    metadata:
      creationTimestamp: null
      name: ttrss-basic-auth
      namespace: ttrss
    type: kubernetes.io/basic-auth

