apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: karakeep

configMapGenerator:
  - name: karakeep-configuration
    literals:
    - NEXTAUTH_URL=https://localhost/
    - KARAKEEP_VERSION=release
