apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
        - name: meilisearch
          image: getmeili/meilisearch:v1.41.0
          env:
            - name: MEILI_NO_ANALYTICS
              value: "true"
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: karakeep-secrets
                  key: nextauth-secret
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: karakeep-secrets
                  key: meili-master-key
            - name: NEXT_PUBLIC_SECRET
              valueFrom:
                secretKeyRef:
                  name: karakeep-secrets
                  key: next-public-secret
          volumeMounts:
            - mountPath: /meili_data
              name: meilisearch
          envFrom:
            - configMapRef:
                name: karakeep-configuration
      volumes:
        - name: meilisearch
          persistentVolumeClaim:
            claimName: meilisearch-pvc
