apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/coder
  - ../base/power_sensor_monitor
  - ../base/ttrss
  - ../base/funkwhale
patchesStrategicMerge:
  - coder.yaml
  - power-sensor-monitor.yaml
  - ttrss.yaml
  - funkwhale.yaml
