apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/power_sensor_monitor
  - ../base/freshrss
  - ../base/funkwhale
  - ../base/syncthing
patchesStrategicMerge:
  - power-sensor-monitor.yaml
  - power-sensor-monitor_http_redir.yaml
  - freshrss.yaml
  - funkwhale.yaml
  - funkwhale_http_redir.yaml
  - syncthing.yaml
