apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    # This must get replaced in the production version...
    # Demo at https://github.com/fluxcd/flux2-kustomize-helm-example/
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: kc0bfv@notmet.net
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - http01:
          ingress:
            class: traefik
