---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kc0bfv-helm-repo
spec:
  interval: 24h
  url: https://kc0bfv.github.io/helm-repo/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: power-sensor-monitor
spec:
  chart:
    spec:
      chart: power-sensor-monitor
      version: '~0.1.0-0'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kc0bfv-helm-repo
      interval: 24h
  interval: 10m
  values:
    nodeSelector:
      node-role.kubernetes.io/master: "true"
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
    resources:
      requests:
        memory: "50Mi"
        cpu: "10m"
      limits:
        memory: "100Mi"
        cpu: "200m"
    ingress:
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
