apiVersion: v1
kind: Pod
metadata:
  name: printenv
  namespace: power-sensor-monitor
spec:
  containers:
  - name: printenv
    image: kc0bfv/power_sensor_monitor
    volumeMounts:
    - mountPath: "/opt/webhook_data"
      name: webhook-catcher-data
    ports:
    - containerPort: 8080
    command: ["printenv"]
    env:
    - name: PORT
      value: "8080"
    - name: URL_BASE
      value: "webhook"
    - name: WRITE_DIR
      value: "/opt/webhook_data/"
    - name: WRITE_KEY
      valueFrome:
        secretKeyRef:
            name: webhook-catcher-keys
            key: writekeydne
    - name: READ_KEY
      valueFrome:
        secretKeyRef:
            name: webhook-catcher-keys
            key: readkey
  volumes:
  - name: webhook-catcher-data
    persistentVolumeClaim:
        claimName: webhook-catcher-data
