---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coder
  namespace: coder
spec:
  values:
    coder:
      env:
        - name: "CODER_ACCESS_URL"
          value: https://coder.devops.notmet.net/
      ingress:
        enable: true
        annotations:
          kubernetes.io/ingress.class: traefik
          cert-manager.io/cluster-issuer: letsencrypt
        host: coder.devops.notmet.net
        tls:
          enable: true
          secretName: coder-tls
