---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coder
  namespace: coder
spec:
  values:
    coder:
      env:
        - name: "CODER_ACCESS_URL"
          value: https://coder.devops.notmet.net/
        - name: CODER_PG_CONNECTION_URL
          valueFrom:
            secretKeyRef:
              name: coder-db-url
              key: url
      ingress:
        enable: true
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          cert-manager.io/cluster-issuer: letsencrypt
        host: coder.devops.notmet.net
        tls:
          enable: true
          secretName: coder-tls
