apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: funkwhale
spec:
  values:
    ingress:
      enabled: true
      host: funkwhale.devops.notmet.net
      tls:
        - secretName: funkwhale-tls
          hosts:
            - funkwhale.devops.notmet.net
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt
