apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ttrss
spec:
  values:
    host: reader.devops.notmet.net
    ingress:
      enabled: true
      tls:
        secretName: ttrss-tls
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.middlewares: ttrss-ttrss-auth@kubernetescrd
