---
apiVersion: v1
kind: Pod
metadata:
  name: db
  namespace: ttrss
  labels:
    app: db
spec:
  containers:
  - name: db
    image: postgres:12-alpine
    volumeMounts:
    - mountPath: "/var/lib/postgresql/data"
      name: database
    env:
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
            name: ttrss-database
            key: username
    - name: POSTGRES_DB
      valueFrom:
        secretKeyRef:
            name: ttrss-database
            key: dbname
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
            name: ttrss-database
            key: password
  volumes:
  - name: database
    persistentVolumeClaim:
        claimName: database
