---
apiVersion: v1
kind: Service
metadata:
  name: ttrss-service
  namespace: ttrss
spec:
  selector:
    app: ttrss-web-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: ttrss
spec:
  selector:
    app: app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
