---
apiVersion: v1
kind: Service
metadata:
  name: ttrss-service
  namespace: ttrss
spec:
  selector:
    app: ttrss-web-nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: ttrss
spec:
  selector:
    app: app
  clusterIP: None
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      name: app
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: ttrss
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      name: postgres
