---
apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: ttrss
spec:
  hostname: app
  containers:
  - name: app
    image: cthulhoo/ttrss-fpm-pgsql-static
    volumeMounts:
    - mountPath: "/var/www/html"
      name: app
    - mountPath: "/opt/tt-rss/config.d"
      name: config
      readOnly: true
    env:
    - name: TTRSS_SELF_URL_PATH
      value: "https://reader/tt-rss/"
    - name: HTTP_PORT
      value: "127.0.0.1:8280"
    - name: TTRSS_DB_USER
      valueFrom:
        secretKeyRef:
            name: ttrss-database
            key: username
    - name: TTRSS_DB_NAME
      valueFrom:
        secretKeyRef:
            name: ttrss-database
            key: dbname
    - name: TTRSS_DB_PASS
      valueFrom:
        secretKeyRef:
            name: ttrss-database
            key: password
  volumes:
  - name: app
    persistentVolumeClaim:
        claimName: app
  - name: config
    persistentVolumeClaim:
        claimName: config
        readOnly: true
---
apiVersion: v1
kind: Pod
metadata:
  name: backups
  namespace: ttrss
spec:
  containers:
  - name: backups
    image: cthulhoo/ttrss-fpm-pgsql-static
    command: ["/opt/tt-rss/dcron.sh", "-f"]
    volumeMounts:
    - mountPath: "/var/www/html"
      name: app
    - mountPath: "/backups"
      name: backups
    env:
    - name: TTRSS_SELF_URL_PATH
      value: "https://reader/tt-rss/"
    - name: HTTP_PORT
      value: "127.0.0.1:8280"
    - name: TTRSS_DB_USER
      valueFrom:
        secretKeyRef:
            name: ttrss-database
            key: username
    - name: TTRSS_DB_NAME
      valueFrom:
        secretKeyRef:
            name: ttrss-database
            key: dbname
    - name: TTRSS_DB_PASS
      valueFrom:
        secretKeyRef:
            name: ttrss-database
            key: password
  volumes:
  - name: app
    persistentVolumeClaim:
        claimName: app
  - name: backups
    persistentVolumeClaim:
        claimName: backups
---
apiVersion: v1
kind: Pod
metadata:
  name: updater
  namespace: ttrss
spec:
  containers:
  - name: updater
    image: cthulhoo/ttrss-fpm-pgsql-static
    command: ["/opt/tt-rss/updater.sh"]
    volumeMounts:
    - mountPath: "/var/www/html"
      name: app
    - mountPath: "/opt/tt-rss/config.d"
      name: config
      readOnly: true
    env:
    - name: TTRSS_SELF_URL_PATH
      value: "https://reader/tt-rss/"
    - name: HTTP_PORT
      value: "127.0.0.1:8280"
    - name: TTRSS_DB_USER
      valueFrom:
        secretKeyRef:
            name: ttrss-database
            key: username
    - name: TTRSS_DB_NAME
      valueFrom:
        secretKeyRef:
            name: ttrss-database
            key: dbname
    - name: TTRSS_DB_PASS
      valueFrom:
        secretKeyRef:
            name: ttrss-database
            key: password
  volumes:
  - name: app
    persistentVolumeClaim:
        claimName: app
  - name: config
    persistentVolumeClaim:
        claimName: config
        readOnly: true
