---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coder
  namespace: coder
spec:
  values:
    postgresql:
      primary:
        nodeSelector:
          node-role.kubernetes.io/master: "true"
        tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/master
    coder:
      env:
        - name: "CODER_ACCESS_URL"
          value: http://coder/
        - name: CODER_PG_CONNECTION_URL
          valueFrom:
            secretKeyRef:
              name: coder-db-url
              key: url
      ingress:
        enable: true
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        host: coder
        #tls:
        #  enable: true
        #  secretName: coder-secret-tls
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
