---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coder
  namespace: coder
spec:
  values:
    ingress:
      enable: true
      annotations:
        kubernetes.io/ingress.class: traefik
      host: coder
