---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coder
  namespace: coder
spec:
  values:
    coder:
      env:
        - name: "CODER_ACCESS_URL"
          value: http://coder/
      ingress:
        enable: true
        annotations:
          kubernetes.io/ingress.class: traefik
        host: coder
        #tls:
        #  enable: true
        #  secretName: coder-secret-tls
