apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: karakeep

configMapGenerator:
  - name: karakeep-configuration
    behavior: merge
    literals:
    - NEXTAUTH_URL=https://karakeep-cust/
    - KARAKEEP_VERSION=release
    - DISABLE_SIGNUPS=true
