apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: karakeep-web-ingress
  namespace: karakeep
spec:
  rules:
  - host: "karakeep-cust"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "web"
            port:
              number: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: karakeep-redirect
  namespace: karakeep
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: karakeep-karakeep-redirect@kubernetescrd
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: "karakeep-cust"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web
            port:
              number: 3000
