apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/coder
  - ../base/nginx
  - ../base/power_sensor_monitor
  - ../base/ttrss
patchesStrategicMerge:
  - coder-ingress.yaml
  - nginx-ingress.yaml
  #- power-sensor-monitor-ingress.yaml
  - ttrss-ingress.yaml
