apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base/nginx
- ../base/karakeep
- karakeep.yaml
#- ../base/power_sensor_monitor
#- ../base/syncthing
#- ../base/freshrss
patchesStrategicMerge:
- nginx-ingress.yaml
- karakeep-ingress.yaml
#- power-sensor-monitor.yaml
