apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base/nginx
- ../base/karakeep
#- ../base/power_sensor_monitor
#- ../base/syncthing
#- ../base/freshrss
patchesStrategicMerge:
- nginx-ingress.yaml
- karakeep-ingress.yaml
#- power-sensor-monitor.yaml

# For karakeep
configMapGenerator:
  - name: karakeep-configuration
    behavior: merge
    literals:
    - NEXTAUTH_URL=https://karakeep-cust/
    - KARAKEEP_VERSION=release
    - DISABLE_SIGNUPS=true
