apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/coder
  - ../base/nginx
  - ../base/power_sensor_monitor
patchesStrategicMerge:
  - coder-ingress.yaml
  - coder-db-creds-sealed.yaml
  - coder-db-url-sealed.yaml
  - nginx-ingress.yaml
  - webhook-catcher-keys-sealed.yaml
