apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ttrss
spec:
  values:
    nodeSelector:
      node-role.kubernetes.io/master: "true"
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
