---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coder-db
  namespace: coder
spec:
  chart:
    spec:
      chart: postgresql
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: v11
  values:
    postgresql:
      auth:
        username: coder
        password: coder
        database: coder
        #existingSecret: coder-db-creds
      primary:
        persistence.size: "10Gi"
  interval: 1m0s
