---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ananace
spec:
  interval: 24h
  url: https://ananace.gitlab.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: funkwhale
spec:
  chart:
    spec:
      chart: funkwhale
      version: '~1.0.0'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ananace
      interval: 24h
  interval: 10m
  values:
    postgresql:
      primary:
        nodeSelector:
          node-role.kubernetes.io/master: "true"
        tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/master
    redis:
      master:
        nodeSelector:
          node-role.kubernetes.io/master: "true"
        tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/master
    api:
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
    front:
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
    celery:
      beat:
        nodeSelector:
          node-role.kubernetes.io/master: "true"
        tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/master
      worker:
        nodeSelector:
          node-role.kubernetes.io/master: "true"
        tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/master
